apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - catalogue/manifest.yaml
  - user/manifest.yaml
  - cart/manifest.yaml
  - shipping/manifest.yaml
  - payment/manifest.yaml
  - frontend/manifest.yaml
  - mongodb/manifest.yaml
  - mysql/manifest.yaml
  - redis/manifest.yaml
  - rabbitmq/manifest.yaml